/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulate */
        post: operations["simulate_api_simulate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GratingDTO */
        GratingDTO: {
            /** N */
            n: number;
            /**
             * K
             * @default 0
             */
            k: number;
            /** Fillfactor */
            fillFactor: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LayerDTO */
        LayerDTO: {
            /** Name */
            name: string;
            /** Thicknessnm */
            thicknessNm: number;
            /** N */
            n: number;
            /**
             * K
             * @default 0
             */
            k: number;
            grating?: components["schemas"]["GratingDTO"] | null;
        };
        /**
         * Polarization
         * @description 偏光。S=TE、P=TM。
         * @enum {string}
         */
        Polarization: "s" | "p";
        /** SimulationRequest */
        SimulationRequest: {
            /** Wlmin */
            wlMin: number;
            /** Wlmax */
            wlMax: number;
            /** Wlpoints */
            wlPoints: number;
            /**
             * Thetadeg
             * @default 0
             */
            thetaDeg: number;
            /** @default s */
            pol: components["schemas"]["Polarization"];
            /** Periodnm */
            periodNm: number;
            /** Numorders */
            numOrders: number;
            /** Layers */
            layers: components["schemas"]["LayerDTO"][];
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Wavelengths */
            wavelengths: number[];
            /** R */
            R: number[];
            /** T */
            T: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    simulate_api_simulate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
